### PR TITLE
Product review

### PR DESCRIPTION
**Pull request by swtmak**
Incorporates feedback from review by UX team and trial team.
Adds/clarifies steps that were missing/unclear.

### CODE REVIEW

**Comment by swtmak** [comment]
Heh ... that was mostly Greek to me :-)
What would "a git rebase" do/fix?

**Comment by sbourlon** [comment]
@swtmak git rebase will put your change on top of the current master branch. I hope I didn't switch to Latin ;-)

**Comment by swtmak** [comment]
Ah, ok ... I think I understand, and think I'm fine with that suggestion.
Thanks for the explanation :-)

**Comment by sbourlon** [comment]
Pushed from a difference channel.

**Pull request closed without merging**
